spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "rust-outbound-pg-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "outbound-pg"

[component.outbound-pg]
environment = { DB_URL = "host=localhost user=postgres dbname=spin_dev" }
source = "target/wasm32-wasi/release/rust_outbound_pg.wasm"
allowed_outbound_hosts = ["postgres://localhost"]
[component.outbound-pg.build]
command = "cargo build --target wasm32-wasi --release"
