manifest_version = "1"
id = "http-rust"
description = "HTTP request handler using Rust"

[parameters]
project-description = { type = "string",  prompt = "Project description" }
http-base = { type = "string", prompt = "HTTP base", default = "/", pattern = "^/\\S*$" }
http-path = { type = "string", prompt = "HTTP path", default = "/...", pattern = "^/\\S*$" }