spin_manifest_version = 2

[application]
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = "Demo of calling MySQL from a Spin application"
name = "rust-outbound-mysql"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "rust-outbound-mysql"

[component.rust-outbound-mysql]
environment = { DB_URL = "mysql://spin:spin@127.0.0.1/spin_dev" }
source = "target/wasm32-wasi/release/rust_outbound_mysql.wasm"
allowed_outbound_hosts = ["mysql://127.0.0.1"]
[component.rust-outbound-mysql.build]
command = "cargo build --target wasm32-wasi --release"
