[package]
name = "spin-runtime-config"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
spin-factor-key-value = { path = "../factor-key-value" }
spin-factor-key-value-azure = { path = "../factor-key-value-azure" }
spin-factor-key-value-redis = { path = "../factor-key-value-redis" }
spin-factor-key-value-spin = { path = "../factor-key-value-spin" }
spin-factor-llm = { path = "../factor-llm" }
spin-factor-observe = { path = "../factor-observe" }
spin-factor-outbound-http = { path = "../factor-outbound-http" }
spin-factor-outbound-mqtt = { path = "../factor-outbound-mqtt" }
spin-factor-outbound-mysql = { path = "../factor-outbound-mysql" }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-factor-outbound-pg = { path = "../factor-outbound-pg" }
spin-factor-outbound-redis = { path = "../factor-outbound-redis" }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }
spin-factors = { path = "../factors" }
toml = "0.8"

[lints]
workspace = true
