[package]
name = "spin-factor-outbound-networking"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
futures-util = "0.3"
ipnet = "2.9.0"
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }
spin-factors = { path = "../factors" }
# TODO: merge with this crate
spin-outbound-networking = { path = "../outbound-networking" }
tracing = { workspace = true }

[lints]
workspace = true
