spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that returns the arguments the program started with, the environment variables set, and current time"
name = "wagi-hello-world"
trigger = { type = "http" }
version = "1.0.0"

[[component]]
id = "env"
source = "target/wasm32-wasi/release/wagihelloworld.wasm"
[component.trigger]
route = "/env"
executor =  { type = "wagi" } # _start (the default entrypoint) is automatically mapped to main()
[component.build]
command = "cargo build --target wasm32-wasi --release"
