spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that demonstrates HTTP routing."
name = "spin-rust-router"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "route"

[component.route]
source = "target/wasm32-wasi/release/http_rust_router.wasm"
description = "A component that internally routes HTTP requests."
[component.route.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml", "spin.toml"]
