spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A redis application."
name = "spin-redis"
version = "0.1.0"

[application.trigger.redis]
address = "redis://localhost:6379"

[[trigger.redis]]
channel = "messages"
component = "echo-message"

[component.echo-message]
source = "target/wasm32-wasi/release/spinredis.wasm"
[component.echo-message.build]
command = "cargo build --target wasm32-wasi --release"
