[package]
name = "spin-serde"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
base64 = "0.22.1"
semver = { version = "1.0", features = ["serde"] }
serde = { workspace = true }
wasm-pkg-common = { workspace = true }
