[package]
name = "spin-factors"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
serde = "1.0"
spin-app = { path = "../app" }
spin-factors-derive = { path = "../factors-derive" }
thiserror = "1.0"
# TODO: make this optional and behind a feature flag
toml = "0.8"
tracing = { workspace = true }
wasmtime = { workspace = true }

[lints]
workspace = true
