[package]
name = "spin-factors"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
spin-app = { path = "../app" }
spin-factors-derive = { path = "../factors-derive" }
thiserror = { workspace = true }
# TODO: make this optional and behind a feature flag
toml = { workspace = true }
wasmtime = { workspace = true }

[lints]
workspace = true
