[package]
name = "spin-redis-engine"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
serde = "1.0.188"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-trigger = { path = "../trigger" }
spin-world = { path = "../world" }
redis = { version = "0.21", features = ["tokio-comp"] }
tracing = { workspace = true }

[dev-dependencies]
spin-testing = { path = "../testing" }
