[package]
name = "spin-redis-engine"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
serde = "1"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-trigger-new = { path = "../trigger-new" }
redis = { version = "0.21", features = [ "tokio-comp" ] }
tracing = { version = "0.1", features = [ "log" ] }

[dependencies.wit-bindgen-wasmtime]
git = "https://github.com/bytecodealliance/wit-bindgen"
rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba"
features = ["async"]

[dev-dependencies]
spin-testing = { path = "../testing" }
