[package]
name = "spin-sqlite"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
spin-core = { path = "../core" }
spin-app = { path = "../app" }
spin-world = { path = "../world" }
table = { path = "../table" }
tokio = "1"
