[package]
name = "spin-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
spin-core = { path = "../core" }
spin-app = { path = "../app" }
spin-key-value = { path = "../key-value" }
spin-world = { path = "../world" }
anyhow = "1.0"
wit-bindgen-wasmtime = { workspace = true }
rusqlite = { version = "0.29.0", features = [ "bundled" ] }
rand = "0.8"
once_cell = "1"
tokio = "1"