[package]
name = "spin-sqlite"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
spin-core = { path = "../core" }
spin-app = { path = "../app" }
spin-key-value = { path = "../key-value" }
spin-world = { path = "../world" }
anyhow = "1.0"
wit-bindgen-wasmtime = { workspace = true }
tokio = "1"