[package]
name = "spin-sqlite"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["rc"] }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-factors = { path = "../factors" }
spin-locked-app = { path = "../locked-app" }
spin-sqlite-inproc = { path = "../sqlite-inproc" }
spin-sqlite-libsql = { path = "../sqlite-libsql" }
spin-world = { path = "../world" }
table = { path = "../table" }
tokio = "1"
toml = "0.8"
