spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Demonstrates outbound HTTP calls"
name = "spin-outbound-http"
version = "1.0.0"

[[trigger.http]]
route = "/outbound"
component = "outbound-http"

[[trigger.http]]
route = "/wildcard"
component = "outbound-http-wildcard"

[[trigger.http]]
route = "/outbound-to-hello-component"
component = "outbound-http-to-same-app"

[[trigger.http]]
route = "/hello"
component = "hello-component"

[component.outbound-http]
source = "outbound-http/target/wasm32-wasi/release/http_rust_outbound_http.wasm"
allowed_http_hosts = ["foo.com"]
allowed_outbound_hosts = ["https://random-data-api.fermyon.app"]
[component.outbound-http.build]
workdir = "outbound-http"
command = "cargo build --target wasm32-wasi --release"

[component.outbound-http-wildcard]
source = "outbound-http/target/wasm32-wasi/release/http_rust_outbound_http.wasm"
allowed_outbound_hosts = ["https://*:*"]
[component.outbound-http-wildcard.build]
workdir = "outbound-http"
command = "cargo build --target wasm32-wasi --release"

[component.outbound-http-to-same-app]
source = "outbound-http-to-same-app/target/wasm32-wasi/release/outbound_http_to_same_app.wasm"
# To make outbound calls to components in the same Spin app, use the special value self.
allowed_outbound_hosts = ["http://self"]
[component.outbound-http-to-same-app.build]
workdir = "outbound-http-to-same-app"
command = "cargo build --target wasm32-wasi --release"

[component.hello-component]
source = "http-hello/target/wasm32-wasi/release/http_hello.wasm"
description = "A simple component that returns hello."
[component.hello-component.build]
workdir = "http-hello"
command = "cargo build --target wasm32-wasi --release"
