spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that streams a chunked file as an HTTP response"
name = "spin-wasi-http-streaming-file"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "spin-wasi-http-streaming-file"

[component.spin-wasi-http-streaming-file]
source = "target/wasm32-wasi/release/spin_wasi_http_streaming_file.wasm"
files = [{ source = ".", destination = "/" }]
[component.spin-wasi-http-streaming-file.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
