[package]
name = "spin-config"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2f46ce4cc072107153da0cefe15bdc69aa5b84d0" }

[dev-dependencies]
toml = "0.5"
