[package]
name = "spin-loader"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bindle = { workspace = true }
bytes = "1.1.0"
futures = "0.3.17"
glob = "0.3.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
outbound-http = { path = "../outbound-http" }
path-absolutize = "3.0.11"
regex = "1.5.4"
reqwest = "0.11.9"
sha2 = "0.10.1"
serde = { version = "1.0", features = [ "derive" ] }
spin-manifest = { path = "../manifest" }
tempfile = "3.3.0"
tokio = { version = "1.23", features = [ "full" ] }
tokio-util = "0.6"
toml = "0.5"
tracing = { workspace = true }
walkdir = "2.3.2"
