[package]
name = "spin-loader"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bindle = { version = "0.8.0", default-features = false, features = ["client"] }
bytes = "1.1.0"
dirs = "4.0"
fs_extra = "1.2.0"
futures = "0.3.17"
glob = "0.3.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
path-absolutize = "3.0.11"
regex = "1.5.4"
reqwest = "0.11.9"
sha2 = "0.10.1"
serde = { version = "1.0", features = [ "derive" ] }
spin-config = { path = "../config" }
spin-manifest = { path = "../manifest" }
tempfile = "3.3.0"
tokio = { version = "1.11", features = [ "full" ] }
tokio-util = "0.6"
toml = "0.5"
tracing = { version = "0.1", features = [ "log" ] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3.7", features = [ "env-filter" ] }
walkdir = "2.3.2"
