[package]
name = "spin-loader"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
glob = { workspace = true }
path-absolutize = { version = "3", features = ["use_unix_paths_on_wasm"] }
reqwest = "0.12"
semver = "1"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
spin-common = { path = "../common" }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-locked-app = { path = "../locked-app" }
spin-manifest = { path = "../manifest" }
spin-serde = { path = "../serde" }
tempfile = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
wasm-pkg-client = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
ui-testing = { path = "../ui-testing" }

[features]
default = ["async-io"]
async-io = ["tokio/fs"]

[[test]]
name = "ui"
path = "tests/ui.rs"
harness = false
