[package]
name = "spin-loader"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bytes = "1.1.0"
dirs = "4.0"
futures = "0.3.17"
glob = "0.3.0"
indexmap = { version = "1" }
itertools = "0.10.3"
lazy_static = "1.4.0"
mime_guess = { version = "2.0" }
path-absolutize = { version = "3.0.11", features = ["use_unix_paths_on_wasm"] }
regex = "1.5.4"
reqwest = "0.11.9"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10.8"
shellexpand = "3.1"
spin-common = { path = "../common" }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-locked-app = { path = "../locked-app" }
spin-manifest = { path = "../manifest" }
spin-serde = { path = "../serde" }
tempfile = "3.8.0"
terminal = { path = "../terminal" }
thiserror = "1.0.49"
tokio = "1.23"
tokio-util = "0.6"
toml = "0.8.2"
tracing = { workspace = true }
walkdir = "2.3.2"
wasm-pkg-loader = "0.4.1"

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "macros"] }
ui-testing = { path = "../ui-testing" }

[features]
default = ["async-io"]
async-io = ["tokio/fs"]

[[test]]
name = "ui"
path = "tests/ui.rs"
harness = false
