[package]
name = "spin-loader"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1"
async-trait = "0.1.52"
bytes = "1.1.0"
dirs = "4.0"
dunce = "1.0"
futures = "0.3.17"
glob = "0.3.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
mime_guess = { version = "2.0" }
outbound-http = { path = "../outbound-http" }
path-absolutize = "3.0.11"
regex = "1.5.4"
reqwest = "0.11.9"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1"
spin-common = { path = "../common" }
spin-config = { path = "../config" }
spin-manifest = { path = "../manifest" }
tempfile = "3.3.0"
terminal = { path = "../terminal" }
tokio = { version = "1.23", features = [ "full" ] }
tokio-util = "0.6"
toml = "0.5"
tracing = { workspace = true }
walkdir = "2.3.2"

[features]
default = ["local"]
local = []