spin_manifest_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that makes concurrent outbound HTTP requests."
name = "spin-wasi-http-async"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "wasi-http-async"
source = "target/wasm32-wasi/release/wasi_http_rust_streaming_outgoing_body.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
