spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "An application that makes concurrent outbound HTTP requests."
name = "spin-wasi-http-async"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "wasi-http-async"

[component.wasi-http-async]
source = "target/wasm32-wasi/release/wasi_http_rust_streaming_outgoing_body.wasm"
allowed_outbound_hosts = ["http://*:*", "https://*:*"]
[component.wasi-http-async.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
