[package]
name = "spin-runtime-factors"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
llm = ["spin-factor-llm/llm"]
llm-metal = ["spin-factor-llm/llm-metal"]
llm-cublas = ["spin-factor-llm/llm-cublas"]

[dependencies]
anyhow = { workspace = true }
clap = { version = "3.1.18", features = ["derive", "env"] }
spin-common = { path = "../common" }
spin-factor-key-value = { path = "../factor-key-value" }
spin-factor-llm = { path = "../factor-llm" }
spin-factor-outbound-http = { path = "../factor-outbound-http" }
spin-factor-outbound-mqtt = { path = "../factor-outbound-mqtt" }
spin-factor-outbound-mysql = { path = "../factor-outbound-mysql" }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-factor-outbound-pg = { path = "../factor-outbound-pg" }
spin-factor-outbound-redis = { path = "../factor-outbound-redis" }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }
spin-factors = { path = "../factors" }
spin-factors-executor = { path = "../factors-executor" }
spin-runtime-config = { path = "../runtime-config" }
spin-trigger = { path = "../trigger" }
terminal = { path = "../terminal" }
tracing = { workspace = true }

[lints]
workspace = true
