[package]
name = "spin-trigger2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "3.1.18", features = ["derive", "env"] }
ctrlc = { version = "3.2", features = ["termination"] }
futures = "0.3"
spin-runtime-config = { path = "../runtime-config" }
sanitize-filename = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spin-app = { path = "../app" }
spin-common = { path = "../common" }
spin-componentize = { path = "../componentize" }
spin-core = { path = "../core" }
spin-factor-key-value = { path = "../factor-key-value" }
spin-factor-outbound-http = { path = "../factor-outbound-http" }
spin-factor-outbound-mqtt = { path = "../factor-outbound-mqtt" }
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-factor-outbound-pg = { path = "../factor-outbound-pg" }
spin-factor-outbound-mysql = { path = "../factor-outbound-mysql" }
spin-factor-outbound-redis = { path = "../factor-outbound-redis" }
spin-factor-sqlite = { path = "../factor-sqlite" }
spin-factor-variables = { path = "../factor-variables" }
spin-factor-wasi = { path = "../factor-wasi" }
spin-factors = { path = "../factors" }
spin-factors-executor = { path = "../factors-executor" }
spin-telemetry = { path = "../telemetry" }
tokio = { version = "1.23", features = ["fs"] }
terminal = { path = "../terminal" }
tracing = { workspace = true }

[lints]
workspace = true
