manifest_version = "1"
id = "redis-go"
description = "Redis message handler using (Tiny)Go"

[parameters]
project-description = { type = "string",  prompt = "Project description" }
redis-address = { type = "string", prompt = "Redis address", default = "redis://localhost:6379" }
redis-channel = { type = "string", prompt = "Redis channel" }