[package]
name = "outbound-redis"
version = "0.2.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
owning_ref = "0.4.1"
redis = { version = "0.21", features = [ "tokio-comp" ] }
spin-engine = { path = "../engine" }
spin-manifest = { path = "../manifest" }
tracing = { version = "0.1", features = [ "log" ] }
tracing-futures = "0.2"

[dependencies.wit-bindgen-wasmtime]
git = "https://github.com/bytecodealliance/wit-bindgen"
rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba"
features = ["async"]