[package]
name = "outbound-redis"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
redis = { version = "0.21", features = ["tokio-comp", "tokio-native-tls-comp"] }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
table = { path = "../table" }
tokio = { version = "1", features = ["sync"] }
tracing = { workspace = true }
