[package]
name = "spin-locked-app"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
ouroboros = "0.18.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
spin-serde = { path = "../serde" }
thiserror = "1.0"
