spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "Simple example using the llm sdk."
name = "tinygo-llm"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "tinygo-llm"

[component.tinygo-llm]
source = "main.wasm"
allowed_outbound_hosts = []
ai_models = ["llama2-chat", "all-minilm-l6-v2"]
[component.tinygo-llm.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
