spin_manifest_version = "1"
authors = ["{{authors}}"]
description = "{{project-description}}"
name = "{{project-name}}"
trigger = { type = "http", base = "{{http-base}}" }
version = "0.1.0"

[[component]]
id = "{{project-name | kebab_case}}"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "{{http-path}}"
executor = { type = "wagi" }
[component.build]
command = "zig build-exe -O ReleaseSmall -target wasm32-wasi main.c -lc"
watch = ["**/*.c"]
