[package]
name = "spin-outbound-networking"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0"
ipnet = "2.9.0"
spin-locked-app = { path = "../locked-app" }
terminal = { path = "../terminal" }
url = "2.4.1"
urlencoding = "2.1"
