[package]
name = "key-value-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
once_cell = "1"
rusqlite = { version = "0.28.0", features = [ "bundled" ] }
tokio = "1"
wit-bindgen-wasmtime = { workspace = true }
key-value = { path = "../key-value" }
