[package]
name = "spin-factor-outbound-redis"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
spin-factor-outbound-networking = { path = "../factor-outbound-networking" }
spin-factors = { path = "../factors" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
tracing = { workspace = true }
table = { path = "../table" }
redis = { version = "0.21", features = ["tokio-comp", "tokio-native-tls-comp", "aio"] }


[dev-dependencies]
spin-factors-test = { path = "../factors-test" }
tokio = { version = "1", features = ["macros", "rt"] }
spin-factor-variables = { path = "../factor-variables" }

# wasmtime-wasi-http = { workspace = true }
[lints]
workspace = true
