[package]
name = "spin-publish"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
bindle = { workspace = true }
dunce = "1.0"
futures = "0.3.14"
itertools = "0.10.3"
mime_guess = { version = "2.0" }
reqwest = "0.11"
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
spin-loader = { path = "../loader" }
thiserror = "1.0.37"
tokio = "1.16.1"
toml = "0.5"
