[package]
name = "spin-publish"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
async-trait = "0.1.52"
bindle = { version = "0.8.0", default-features = false, features = ["client"] }
dunce = "1.0"
futures = "0.3.14"
itertools = "0.10.3"
mime_guess = { version = "2.0" }
path-absolutize = "3.0.11"
reqwest = "0.11"
semver = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
sha2 = "0.10.1"
spin-loader = { path = "../loader" }
tempfile = "3.3.0"
tokio = "1.16.1"
toml = "0.5"
