[package]
name = "spin-telemetry"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
http0 = { version = "0.2.9", package = "http" }
http1 = { version = "1.0.0", package = "http" }
opentelemetry = { version = "0.22.0", features = [ "metrics", "trace"] }
opentelemetry_sdk = { version = "0.22.1", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.15.0", default_features=false, features = ["http-proto", "trace", "http", "reqwest-client", "metrics", "grpc-tonic"] }
opentelemetry-semantic-conventions = "0.14.0"
tracing = { version = "0.1.37", features = ["log"] }
tracing-appender = "0.2.2"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json", "registry"] }
url = "2.2.2"
lazy_static = "1.4.0"
paste = "1.0.14"