[package]
name = "spin-key-value"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
tokio = { version = "1", features = ["macros", "sync"] }
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
table = { path = "../table" }
tracing = { workspace = true }
lru = "0.9.0"
