spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/event_grid_validation.wasm"
[component.trigger]
route = "/"
[component.build]
command = "cargo build --target wasm32-wasi --release"
