[package]
name = "spin-manifest"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0.75"
indexmap = { version = "1", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
spin-serde = { path = "../serde" }
thiserror = "1"
toml = { version = "0.8.0", features = ["preserve_order"] }
url = "2.4.1"

[dev-dependencies]
anyhow = "1.0.75"
glob = "0.3.1"
serde_json = "1.0"
ui-testing = { path = "../ui-testing" }

[[test]]
name = "ui"
path = "tests/ui.rs"
harness = false
