[package]
name = "spin-manifest"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
indexmap = "1"
serde = { version = "1.0", features = [ "derive" ] }
thiserror = "1"
toml = "0.5"
