[package]
name = "spin-manifest"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[dependencies]
anyhow = "1.0"
indexmap = "1"
serde = { version = "1.0", features = [ "derive" ] }
spin-config = { path = "../config" }
thiserror = "1"
url = "2.2"
