[package]
name = "spin-sdk"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
rust-version = "1.64"

[lib]
name = "spin_sdk"

[dependencies]
anyhow = "1"
bytes = "1"
form_urlencoded = "1.0"
http_types = { package = "http", version = "0.2" }
spin-macro = { path = "macro" }
thiserror = "1.0.37"
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "46fba30bb667a3a4962f63b1cc28b84427b49114" }
routefinder = "0.5.3"
serde_json = { version = "1.0.96", optional = true }
serde = { version = "1.0.163", optional = true }

[features]
default = ["export-sdk-language"]
export-sdk-language = []
json = ["dep:serde", "dep:serde_json"]
experimental = []
