[package]
name = "spin-testing"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
http = "1.0.0"
hyper = "1.0.0"
serde = "1.0.188"
serde_json = "1"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-http = { path = "../http" }
spin-trigger = { path = "../trigger" }
tokio = { version = "1", features = ["macros", "rt"] }
tracing-subscriber = "0.3"
spin-componentize = { workspace = true }
