[package]
name = "spin-testing"
version = "0.2.0"
edition = "2021"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]

[dependencies]
anyhow = "1.0"
http = "0.2"
hyper = "0.14"
serde = "1"
serde_json = "1"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-http = { path = "../http" }
spin-trigger-new = { path = "../trigger-new" }
tokio = { version = "1", features = ["macros", "rt"] }
tracing-subscriber = "0.3"