[package]
name = "spin-templates"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
console = "0.15"
dialoguer = "0.11"
dirs = { workspace = true }
fs_extra = "1"
heck = "0.5"
indexmap = { version = "2", features = ["serde"] }
itertools = { workspace = true }
lazy_static = "1"
liquid = "0.26"
liquid-core = "0.26"
liquid-derive = "0.26"
liquid-lib = "0.26"
path-absolutize = "3"
pathdiff = "0.2"
regex = { workspace = true }
semver = "1"
serde = { workspace = true }
spin-common = { path = "../common" }
spin-manifest = { path = "../manifest" }
tempfile = { workspace = true }
tokio = { version = "1", features = ["fs", "process", "rt", "macros"] }
toml = { workspace = true }
toml_edit = "0.22"
url = { workspace = true }
walkdir = "2"
