[package]
name = "spin-http"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
indexmap = "1"
percent-encoding = "2"
serde = { version = "1.0", features = ["derive"] }
tracing = { workspace = true }
spin-app = { path = "../app" }

[dev-dependencies]
spin-testing = { path = "../testing" }
