[package]
name = "spin-http-engine"
version = "0.2.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = "3"
futures = "0.3"
futures-util = "0.3.8"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
indexmap = "1"
percent-encoding = "2"
spin-manifest = { path = "../manifest" }
spin-engine = { path = "../engine" }
spin-trigger = { path = "../trigger" }
tls-listener = { version = "0.4.0", features = [
    "rustls",
    "hyper-h1",
    "hyper-h2",
] }
tokio = { version = "1.10", features = ["full"] }
tokio-rustls = { version = "0.23.2" }
rustls-pemfile = "0.3.0"
tracing = { version = "0.1", features = ["log"] }
wasi-common = "0.39.1"
wasmtime = { version = "0.39.1", features = ["async"] }

[dependencies.wit-bindgen-wasmtime]
git = "https://github.com/bytecodealliance/wit-bindgen"
rev = "cb871cfa1ee460b51eb1d144b175b9aab9c50aba"
features = ["async"]

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
miniserde = "0.1"
num_cpus = "1"
spin-testing = { path = "../testing" }

[[bench]]
name = "baseline"
harness = false
