[package]
name = "spin-http-engine"
version = "0.1.0"
edition = "2021"
authors = [ "Fermyon Engineering <engineering@fermyon.com>" ]

[lib]
doctest = false

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.1"
cap-std = "0.24.1"
ctrlc = "3.2.1"
futures = "0.3"
futures-util = "0.3.8"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = { version = "0.23.0" }
indexmap = "1.6"
serde = { version = "1.0", features = ["derive"] }
spin-manifest = { path = "../manifest" }
spin-engine = { path = "../engine" }
tls-listener = { version = "0.4.0", features = [
    "rustls",
    "hyper-h1",
    "hyper-h2",
] }
tokio = { version = "1.10", features = ["full"] }
tokio-rustls = { version = "0.23.2" }
rustls-pemfile = "0.3.0"
tracing = { version = "0.1", features = ["log"] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }
url = "2.2"
wagi = { git = "https://github.com/deislabs/wagi", tag = "v0.8.1" }
wasi-cap-std-sync = "0.34"
wasi-common = "0.34"
wasmtime = "0.34"
wasmtime-wasi = "0.34"
wit-bindgen-wasmtime = { git = "https://github.com/bytecodealliance/wit-bindgen", rev = "2f46ce4cc072107153da0cefe15bdc69aa5b84d0" }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["async_tokio"] }
miniserde = "0.1"
num_cpus = "1"
spin-testing = { path = "../testing" }

[[bench]]
name = "baseline"
harness = false